name: Generate Snake SVG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/snake.svg?palette=github-dark
      - name: Sign the commit
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ""
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Push the commit
        run: |
          git add .
          git commit -S -m "Update Snake SVG"
          git push
